spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: EARN_WHILE_TRAVEL
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui


server:
  port: 8600
  servlet:
    context-path: /entry